
%macro _SASTASK_DROPDS(dsname);
	%IF %SYSFUNC(EXIST(&dsname)) %THEN %DO;
		DROP TABLE &dsname;
	%END;
	%IF %SYSFUNC(EXIST(&dsname, VIEW)) %THEN %DO;
		DROP VIEW &dsname;
	%END;
%mend _SASTASK_DROPDS;

%LET _EGCHARTWIDTH=0;
%LET _EGCHARTHEIGHT=0;
/* -------------------------------------------------------------------
   Code generated by SAS Task

   Generated on: Monday, May 16, 2011 at 8:09:29 AM
   By task: Linear

   Input Data: sasuser.query4197
   Server:  Local
   ------------------------------------------------------------------- */

PROC SQL;
%_SASTASK_DROPDS(SASUSER.PREDLinRegPredictions_7YRCHG__95);
%_SASTASK_DROPDS(WORK.SORTTempTableSorted);
%_SASTASK_DROPDS(WORK.TMP1TempTableForPlots);
QUIT;

/* -------------------------------------------------------------------
   Determine the data set's type attribute (if one is defined)
   and prepare it for addition to the data set/view which is
   generated in the following step.
   ------------------------------------------------------------------- */
DATA _NULL_;
	dsid = OPEN("sasuser.query4197", "I");
	dstype = ATTRC(DSID, "TYPE");
	IF TRIM(dstype) = " " THEN
		DO;
		CALL SYMPUT("_EG_DSTYPE_", "");
		CALL SYMPUT("_DSTYPE_VARS_", "");
		END;
	ELSE
		DO;
		CALL SYMPUT("_EG_DSTYPE_", "(TYPE=""" || TRIM(dstype) || """)");
		IF VARNUM(dsid, "_NAME_") NE 0 AND VARNUM(dsid, "_TYPE_") NE 0 THEN
			CALL SYMPUT("_DSTYPE_VARS_", "_TYPE_ _NAME_");
		ELSE IF VARNUM(dsid, "_TYPE_") NE 0 THEN
			CALL SYMPUT("_DSTYPE_VARS_", "_TYPE_");
		ELSE IF VARNUM(dsid, "_NAME_") NE 0 THEN
			CALL SYMPUT("_DSTYPE_VARS_", "_NAME_");
		ELSE
			CALL SYMPUT("_DSTYPE_VARS_", "");
		END;
	rc = CLOSE(dsid);
	STOP;
RUN;

/* -------------------------------------------------------------------
   Data set WORK._7YRCHG__9360 does not need to be sorted.
   ------------------------------------------------------------------- */
DATA WORK.SORTTempTableSorted &_EG_DSTYPE_ / VIEW=WORK.SORTTempTableSorted;
	SET sasuser.query4197;
RUN;
TITLE;
TITLE1 "Linear Regression Results";
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %SYSFUNC(DATE(), EURDFDE9.) at %SYSFUNC(TIME(), TIMEAMPM8.)";
PROC REG DATA=WORK.SORTTempTableSorted
	;
	Linear_Regression_Model: MODEL FNCI = USSW2 USSW5 USSW10
		/		SELECTION=NONE
		INCLUDE=0
		STB SS1 CORRB COVB CLB
		ALPHA=0.05
		VIF DW
		noint 
	;

/* user code */
    restrict USSW2 + USSW5 + USSW10 = 1;
/*	restrict USSW2>= 0 USSW5>= 0 USSW10>= 0; */

    OUTPUT OUT=WORK.TMP1TempTableForPlots
		PREDICTED=_predicted1 RESIDUAL=_residual1 STUDENT=_student1
		RSTUDENT=_rstudent1 LCL=_lcl1 LCLM=_lclm1
		UCL=_ucl1 UCLM=_uclm1
		COOKD=_cookd1 DFFITS=_dffits1 H=_h1
		STDI=_stdi1 STDP=_stdp1 STDR=_stdr1
		COVRATIO=_covratio1;

	OUTPUT OUT=SASUSER.PREDLinRegPredictions_7YRCHG__95(LABEL="Linear regression predictions and statistics for sasuser.query4197")
		PREDICTED=predicted_FNCI ;
RUN;
QUIT;

TITLE;
TITLE1 "Regression Analysis Plots";
AXIS1 MAJOR=(NUMBER=5) WIDTH=1;
AXIS2 OFFSET=(10 PCT) WIDTH=1;
AXIS3 MAJOR=(NUMBER=5) OFFSET=(5 PCT) WIDTH=1;
GOPTIONS PUBLISH;
GOPTIONS xpixels=&_EGCHARTWIDTH ypixels=&_EGCHARTHEIGHT;
PROC GPLOT DATA=WORK.TMP1TempTableForPlots
	;
	WHERE FNCI IS NOT MISSING AND
		USSW2 IS NOT MISSING AND
		USSW5 IS NOT MISSING AND
		USSW10 IS NOT MISSING;

/* ********* PREDICTED plots ********* */

	TITLE4 "Observed FNCI by Predicted FNCI";
	SYMBOL1 C=BLUE V=DOT HEIGHT=2PCT INTERPOL=NONE L=1 W=1;
	LABEL _predicted1 = "Predicted FNCI";
	WHERE FNCI IS NOT MISSING AND _predicted1 IS NOT MISSING;
	PLOT FNCI * _predicted1 /
		VAXIS=AXIS1 VMINOR=0 HAXIS=AXIS3 HMINOR=0
		DESCRIPTION = "Observed FNCI by Predicted FNCI"
	;
	RUN;

	TITLE4 "Observed FNCI by USSW2";
	SYMBOL1 C=BLUE V=DOT HEIGHT=2PCT INTERPOL=RL L=1 W=1;
	WHERE FNCI IS NOT MISSING AND USSW2 IS NOT MISSING;
	PLOT FNCI * USSW2 = 1 /
		VAXIS=AXIS1 VMINOR=0 HAXIS=AXIS3 HMINOR=0
		DESCRIPTION = "Observed FNCI by USSW2"
	;
	RUN;

	TITLE4 "Observed FNCI by USSW5";
	SYMBOL1 C=BLUE V=DOT HEIGHT=2PCT INTERPOL=RL L=1 W=1;
	WHERE FNCI IS NOT MISSING AND USSW5 IS NOT MISSING;
	PLOT FNCI * USSW5 = 1 /
		VAXIS=AXIS1 VMINOR=0 HAXIS=AXIS3 HMINOR=0
		DESCRIPTION = "Observed FNCI by USSW5"
	;
	RUN;

	TITLE4 "Observed FNCI by USSW10";
	SYMBOL1 C=BLUE V=DOT HEIGHT=2PCT INTERPOL=RL L=1 W=1;
	WHERE FNCI IS NOT MISSING AND USSW10 IS NOT MISSING;
	PLOT FNCI * USSW10 = 1 /
		VAXIS=AXIS1 VMINOR=0 HAXIS=AXIS3 HMINOR=0
		DESCRIPTION = "Observed FNCI by USSW10"
	;
	RUN;

SYMBOL;
QUIT;

/* -------------------------------------------------------------------
   End of task code.
   ------------------------------------------------------------------- */
RUN; QUIT;
PROC SQL;
%_SASTASK_DROPDS(WORK.SORTTempTableSorted);
%_SASTASK_DROPDS(WORK.TMP1TempTableForPlots);
QUIT;

TITLE; FOOTNOTE;
GOPTIONS RESET=ALL;

